---
title: "RVF_MODELLING"
author: "ARANI"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo=FALSE}
library(tidyverse)
library(readr)
library(dplyr)
library(ggplot2)
library(patchwork)
library(stringr)
library(scales)
library(gtsummary)
library(janitor)

```


```{r reading dataset, echo=FALSE}
dat <- read_csv("Datasets/RVF KAP Survey_CSV.csv")
```





```{r, renaming the columsn}

dat_clean <- dat |>
  # Drop metadata & system columns 
  select(-matches("^meta/|^_|instanceID")) |>

  # Rename
  rename(
    consent             = 1,
    date_interview      = "Date of Interview",
    interviewer         = "Name of Interviewer",
    subcounty           = "Sub-county",
    ward                = "Ward",
    location            = "Location",
    village             = "Village",
    keeps_livestock     = "Do you keep livestock?",
    respondent          = "Respondent",
    respondent_other    = "Others...10",
    role                = "What is your capacity/role?",
    role_other          = "Others...12",
    gender              = "What is your gender?",
    age_group           = "Which of the following best describes your age group?",
    education           = "What is the highest education level you completed?",
    hh_size             = "Number of people in the household?",
    hh_adults           = "Adult",
    hh_children         = "Children",
    income_ksh          = "Average Monthly income in Ksh",
    farming_system      = "What is your farming system?",
    farming_other       = "Others...21",
    livestock_type_raw  = "Type of livestock owned (select all that apply)",
    livestock_other     = "Others...29",
    gps_raw             = "Household GPS Coordinates",
    gps_lat             = "demographics/_gps_latitude",
    gps_lon             = "demographics/_gps_longitude",
    gps_alt             = "demographics/_gps_altitude",
    gps_prec            = "demographics/_gps_precision",
    heard_rvf           = "Have you ever heard about Rift Valley Fever (RVF)?",
    rvf_affects_humans  = "Can RVF affect humans?",
    learn_source_raw    = "How/where did you learn about RVF?",
    learn_other         = "Others (Specify)...51",
    transmit_animal_raw = "How is RVF transmitted to animals?",
    transmit_animal_other = "Others (Specify)...60",
    animals_get_rvf_raw = "What animals can get RVF?",
    vacc_available      = "Is vaccination against RVF available for livestock?",
    worried_season      = "Which season of the year do you get particularly worried about RVF?",
    transmit_human_raw  = "How is RVF transmitted to humans? (Select all that apply)",
    transmit_human_other = "Others (Specify)...77",
    signs_animals_raw   = "What are common signs or symptoms of RVF in animals? (Select all that apply)",
    signs_animals_other = "Others (Specify)...89",
    signs_humans_raw    = "What are common signs or symptoms of RVF in humans? (Select all that apply)",
    signs_humans_other  = "Others (Specify)...101",
    rvf_dangerous       = "Do you agree RVF is a dangerous disease?",
    herd_had_rvf        = "Has your herd ever experienced RVF infection?",
    hh_member_had_rvf   = "Were any of your household members affected by RVF previously?",
    at_risk             = "Are you at risk of RVF infection?",
    concern_community   = "How concerned are you about RVF infection in humans in your community?",
    prevention_possible = "Do you believe the spread of RVF from animals to humans can be prevented?",
    vacc_effectiveness  = "How effective do you think vaccination of animals is in preventing RVF?",
    vaccinates_livestock = "Do you vaccinate your livestock against RVF?",
    mosquito_control    = "How often do you use mosquito control methods around livestock?",
    avoid_sick_animals  = "Do you avoid slaughtering or handling sick or dead animals?",
    avoid_abortus       = "Do you avoid touching an abortus foetus?",
    uses_ppe            = "Do you use protective clothing/gear (e.g., gloves) when handling animals, especially during birthing or slaughtering?",
    cooks_meat          = "Do you thoroughly cook meat before consuming?",
    reports_deaths      = "In the event of abortions or sudden deaths in your livestock, do you report to veterinary or public health authorities?"
  ) |>

  # Rename select-all-that-apply sub-columns 
  rename_with(~ gsub("livestock_owned/", "ls_", .x)) |>
  rename_with(~ gsub("learn_source/", "src_", .x)) |>
  rename_with(~ gsub("transmit_animals/", "ta_", .x)) |>
  rename_with(~ gsub("affected_animals/", "aa_", .x)) |>
  rename_with(~ gsub("transmit_humans/", "th_", .x)) |>
  rename_with(~ gsub("signs_and_symptoms_animals/", "sa_", .x)) |>
  rename_with(~ gsub("signs_and_symptoms_humans/", "sh_", .x)) |>

  # Clean up remaining special characters 
  rename_with(~ gsub("[^a-zA-Z0-9_]", "_", .x)) |>
  rename_with(~ gsub("_+", "_", .x)) |>        # collapse multiple underscores
  rename_with(~ gsub("_$", "", .x)) |>          # strip trailing underscores
  rename_with(tolower)


```

```{r}

dat1 <- dat_clean %>%
  mutate(
    # Dates
    date_interview = as.Date(date_interview),

    # Numeric variables
    hh_size = as.numeric(hh_size),
    hh_adults = as.numeric(hh_adults),
    hh_children = as.numeric(hh_children),
    gps_lat = as.numeric(gps_lat),
    gps_lon = as.numeric(gps_lon),
    gps_alt = as.numeric(gps_alt),
    gps_prec = as.numeric(gps_prec),

    # Categorical variables
    consent = as.factor(consent),
    interviewer = as.factor(interviewer),
    subcounty = as.factor(subcounty),
    ward = as.factor(ward),
    location = as.factor(location),
    village = as.factor(village),
    keeps_livestock = as.factor(keeps_livestock),
    respondent = as.factor(respondent),
    role = as.factor(role),
    gender = as.factor(gender),
    age_group = as.factor(age_group),
    education = as.factor(education),
    income_ksh = as.factor(income_ksh),
    farming_system = as.factor(farming_system)
  )
```

```{r,checking nulls}
dat1 %>%
  summarise(across(everything(), ~sum(is.na(.)))) %>%
  tidyr::pivot_longer(
    everything(),
    names_to = "Variable",
    values_to = "Missing"
  ) %>%
  mutate(
    Percent = round(100 * Missing / nrow(dat1), 2)
  ) %>%
  tbl_summary(
    by = NULL,
    statistic = list(
      Missing ~ "{mean}",
      Percent ~ "{mean}"
    )
  )
```
